# ---------- Stage 1: Builder ----------
FROM node:22-alpine AS builder

WORKDIR /src

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# ---------- Stage 2: Production ----------
FROM node:22-alpine AS production

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD ["npm", "run", "start"]
